== OAuth

We have a bigger picture of the whole flow (that includes backend) at 
xref:backend:net-modulith/authentication-module.adoc#oauth-flow[the backend documentation]. 
However, on this specific page, we will explain the flow of how the frontend 
communicates through a pop-up between two windows to provide a seamless user experience 
when login-in/registering a user on the system.

[plantuml, oauth-popup-flow-diagram, svg]
....
include::partial$modules/auth-module/diagrams/popup.puml[]
....

[.text-center]
_Figure 1. OAuth Popup Sequence Diagram_

* Starting off the idea that the API returns the OAuth URI computed for us, the UI 
should immediately trigger the opening of a new window with a https://developer.mozilla.org/en-US/docs/Web/API/Window/open[popup nature].
* In this popup we will run the OAuth flow (the user will take care of that)
* By the end of the popup flow, a callback (that's provided to the OAuth flow at the beginning) 
is called (this is specific for the _code_ type of flow we also set at the beginning), 
this callback will be of the frontend specifically.
* The callback and frontend uri is run at the popup level, and we extract through query 
params the `code` that's the piece of data we need to continue further, we then send 
this to the parent through a `postMessage()` method that the browser's API exposes, right 
after that the popup self-closes.
* Once the parent receives the code that the popup provided sent, it can then run 
a request to a backend endpoint so that the backend starts _under the hood_ the whole 
process of login/register and finally responding to the frontend with the 
result, _in case of a success:_ We immediately should be greeted with the `Home Screen`.

[IMPORTANT]
====
It's extremely important to state that we need to have configured the **callback uri** 
at the GCloud side, on the specific OAuth client. This has to correspond to both dev 
and prod environments also. Failing to have the callback uri registered will result 
in the OAuth screen to show an error and having no ability to run the authentication 
flow.
====

=== Routing on the frontend

We will always receive specifically at the `Login` screen. Regardless of a user already 
signing-in before, this is a **security-measure**, due to the sensitivy of the information 
the system holds.

At this screen we will ask the user to sign-up or login, regardless of which option is 
picked, we will always throw the user towards a Google OAuth popup, the login screen 
will remain open for the whole duration, and the moment the OAuth screen succeeds it will 
hit a `/redirect-success` route, that has a _blank_ component in charge of extracting 
the `code` query param to then send a message back to the parent component.

The way to open the popup will be with the following code (demo code only):

include::partial$modules/auth-module/code/oauth-start.adoc[]

Once the Google OAuth flow finishes, it will try to hit `/redirect-success` on the 
frontend, and this route is mapped to this blank component in charge of extracting the 
code that's on a query param and sending it back to the parent:

include::partial$modules/auth-module/code/redirect.adoc[]

And at the parent side, we will simply declare a listener for messages, so that the moment 
we receive the `OAuth` message, we can kick off further logic:

include::partial$modules/auth-module/code/parent-react.adoc[]

=== Talking to the backend

It's once the parent screen receives the code from OAuth, that we will send that to 
the backend so that it can do everything on its own, and we wait for a response back:

[source, ts]
----
useEffect(() => {
    async function postAuthCode() {
      const url = new URL('http://localhost:5214/api/v1/auth/o-auth-code/');
      url.searchParams.set('code', eventList[eventList.length - 1]); <1>

      const response = await fetch(url, { method: 'POST' }); <2>
      const responseBody = await response.json();

      if (response.status === 200) { <3>
        navigate('/login', { state: { code: responseBody.code } }); <4>
      }
    }
    if (eventList.length < 1) {
      return;
    }

    postAuthCode();
  }, [eventList]);
----
<1> Always use APIs that are already there to make your life easier, do not hard wire 
or re-invent the wheel.
<2> We make a post to the specific backend endpoint in order to send the code from 
OAuth.
<3> In case the backend responds with a success, we will redirect the user to the home 
screen
<4> We make use of the `useNavigate()` hook to work with React Router's navigation.

=== Notes

* When consuming React Router hooks plus other utilities, tests easily break due to the 
fact that we almost never test from `main.tsx` component that holds the wrapper context. 
It is for this reason that we have to hydrate our components with the correct React Router 
context through a clever usage of re-exports and wrappers
** Under `src/test-utils/testing-library-utils.tsx` you can have a look at how we 
swap out our router for a `MemoryRouter`, this interface enables us to have the consumers 
feeding all properties that you can normally feed to a router and a `render()` function, plus wrapping a component 
(facade pattern), however under the hood we are changing the router implementation.
** When testing a component that requires for us to have a router context, we can 
import this module instead: `import { render, screen } from 'testing-library-utils';` 
** In order for typescript and vitest to resolve all the remaps correctly we have to edit 
two places:
*** On the `tsconfig.app.json` or `tsconfig.json` file we have to add:
+
```
"paths": {
  "testing-library-utils": ["./src/test-utils/testing-library-utils.tsx"]
}
```
*** And on the `vitest.config.ts` side we have to also add:
+
```
resolve: {
  alias: {
    'testing-library-utils': '/src/test-utils/testing-library-utils.tsx',
    src: '/src',
  },
},
```