= Form Libraries for React

Another really important part of the application will be the leveraging of forms in 
order to capture data, both for persistency, but also normal flows that will require 
searching, filtering and other similar interactions.

It is due to this that this prototype is focusing entirely on seeing the capabilities 
of two popular **Form Libraries** for React:

- Formik (integrated with Yup)
- React Hook Form

This prototype has installed both of them and shows different examples of their 
capabilities alongside the type of code that is needed to be written to get them working.

== Project Rundown

This project was created with vite, following the steps:

- `pnpm create vite react-forms` (Select React > Typescript + SWC)
- `pnpm install`

After scaffolding the initial folder structure, we added the dependencies neccesary to 
start consuming the echarts library.

- `pnpm i formik`
- `pnpm i react-hook-form`

The folder structure:

```
- react-forms
|-- src
|   |-- FormikDemo.tsx
|   |-- App.tsx
```

We have the `App` component that renders a `FormikDemo`, as the name implies it will 
leverage all the tools that Formik provides to show a demo of how a fully setup form in 
Formik will look and behave like.

== Cross Cutting Concerns

=== Formik

When it comes to Formik, besides the basic tutorial rundown, it has many other examples 
in the docs about async calls, about instant-feedback on type, API requests for 
other field validations or calculations, besides Material UI's integrations. So it 
covers many other use cases that will vary heavily on the requirements of the application.