= Multi Factor Authentication

Source: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/mfa?view=aspnetcore-9.0[MS Docs]

Multi-factor authentication (MFA) is a process in which a user is requested during 
a sign-in event for additional forms of identification. This prompt could be to enter 
a code from a cellphone, use a FIDO2 key, or to provide a fingerprint scan. **When 
you require a second form of authentication, security is enhanced. The additional 
factor isn't easily obtained or duplicated by a cyberattacker.**

MFA requires at least two or more types of proof for an identity like something you 
know, something you possess, or biometric validation for the user to authenticate.

Two-factor authentication (2FA) is like a subset of MFA, but the difference being that 
MFA can require two or more factors to prove the identity.

_Small note:_ 2FA is supported by default when using ASP.NET Core Identity. To enable 
or disable 2FA for a specific user, set the `IdentityUser<TKey>.TwoFactorEnabled` 
property.

Inside of MFA, there's **TOTP**, (Time-based One-time Password Algorithm). Compliant 
apps such as Microsoft Authenticator and Google Authenticator can be tied to any 
implementation following said algorithm.

== 2FA and TOTP

Just as a preamble, we have RFCs with all details when it comes to how these algorithms 
should work and their considerations: https://datatracker.ietf.org/doc/html/rfc6238[RFC 6238] 
and https://datatracker.ietf.org/doc/html/rfc4226[RFC 4226].

In short we have to generate a key, (as per _OWASP Recommendations_ these should be 
random, could even be put on a rotation, and should also use strong hashing algorithms, 
such as SHA-512). And with this key we can then generate a URL that could be encoded 
to a QR. Said URL should follow the `otpauth://` URL format. That would be a standard. 
And in there through query params, we could be passing metadata that can then the application 
use as inputs. Once it saves this TOTP, it should be generating codes in time that we 
can then validate on the backend side with the same key we used.

== Project Rundown

This is another ASP.NET Restful API, it focuses on the leverage of two libraries 
`QRCoder` and `Otp.NET`. One will make sure of generating all the neccesary pieces 
of information neccesary for the TOTP algorithm to take place. And the other one 
will be focused entirely on generating a QR Code that can be then read by an Auth 
App, and then start generating on its own a TOTP.

== Cross-Cutting Concerns

=== Logging

=== Security