= Multi Factor Authentication

include::partial$mfa/mfa.adoc[]

== 2FA and TOTP

Just as a preamble, we have RFCs with all details when it comes to how these algorithms 
should work and their considerations: https://datatracker.ietf.org/doc/html/rfc6238[RFC 6238] 
and https://datatracker.ietf.org/doc/html/rfc4226[RFC 4226].

In short we have to generate a key, (as per _OWASP Recommendations_ these should be 
random, could even be put on a rotation, and should also use strong hashing algorithms, 
such as SHA-512). And with this key we can then generate a URL that could be encoded 
to a QR. Said URL should follow the `otpauth://` URL format. That would be a standard. 
And in there through query params, we could be passing metadata that can then the application 
use as inputs. Once it saves this TOTP, it should be generating codes in time that we 
can then validate on the backend side with the same key we used.

== Project Rundown

This is another ASP.NET Restful API, it focuses on the leverage of two libraries 
`QRCoder` and `Otp.NET`. One will make sure of generating all the neccesary pieces 
of information neccesary for the TOTP algorithm to take place. And the other one 
will be focused entirely on generating a QR Code that can be then read by an Auth 
App, and then start generating on its own a TOTP.

At a physical level the folder structure follows the solution structure:

```
- TotpPrototype
|-- src
|   |-- TotpPrototype.Application
|   |   |-- TotpFunctions.cs
|   |   |-- Program.cs
|-- test
```

We don't need much else in here since it's pretty self-contained, the endpoints are 
as follows:

/api/generate-key::
This endpoint focuses solely on the usage of the `OtpNet`, it will generate a random 
key (secret) at byte level, and it will then encode those bytes into base32 so 
that we can print a string.
/api/generate-qr::
This endpoint receives one request param under `secret=<KEY>`, and it will then try 
to save locally a QR that an Authentication App can scan and add to its vault.
/api/validate-code::
This endpoint will receive the TOTP sent through a request param `totp=<CODE>`, 
and the key to validate it with through `secret=<SECRET>` in base32. It will then 
in that specific point in time attempt to return if the code is valid or not.

== Cross-Cutting Concerns

include::partial$mfa/cross-cutting-concerns.adoc[]