= Google OAuth 2.0

include::partial$o-auth/google-oauth-2.adoc[]

== Google OAuth Setup

include::partial$o-auth/google-oauth-setup.adoc[]

== Usage of APIs for authentication

include::partial$o-auth/api-usage.adoc[]

== Project Rundown

include::partial$o-auth/project-rundown.adoc[]

=== Folder Structure

We are skipping over architecture patterns since this is a prototype (at least for now), 
we are focusing on quickly trying out the ideas we have in mind, in short, this is 
a deliverable from a _Spike_ that concerns OAuth's capabilities in a web app integrated 
with .NET.

The structure for the solution closely resembles its physical folder structure:

```
- GoogleOAuthPrototype
|-- src
|   |-- GoogleOAuthPrototype.Application
|   |   |-- Constants
|   |   |-- Files
|   |   |   |-- client_secrets.json
|   |   |-- POCO
|   |   |-- Services
|-- test
|   |-- GoogleOAuthPrototype.Application.UnitTests
```

The `client_secrets.json` file is there for illustrative purposes since it will 
never be comitted to version control. But it should be here as a base line of the 
source of truth when it comes to connecting to the virtual application that is living 
at Google Cloud. The code has been adapted so that this file is neccesary to be there 
(you have to get the file manually through secure means), put it in the path, and 
that way the prototype will be able to boot up, consume the google credentials and 
work as intended. This is neccesary to avoid leaking sensitive information.

Besides that, folders are separated by technical concerns (this is not recommended for 
big projects), but since the prototype is so small, then it's fine for simplicity's 
sake alongside a clear pathway into component visualization when it comes to enumerating 
all that's needed in order to integrate with Google Auth.

== Cross-Cutting Concerns

=== Configurations and Security

include::partial$o-auth/cross-cutting-concerns.adoc[]