= React Hook Form

== General Usage

Based on the documentation at https://react-hook-form.com/get-started[React Hook Form].

React Hook Form's design and philosophy focus on user and developer experience. 
The library aims to provide users with a smoother interaction experience by fine-tuning 
the performance and improving accesibility. Some of the performance enhancements 
include:

- Form state subscription model through the proxy
- Avoiding unnecessary computation
- Isolating component re-rendering when required

It aims at improving the user experience while users interact with the application .
As for the developers, there's built-in validation closely aliged with HTML standards 
allowing further extension with powerful validation methods and integration with 
schema validation natively. It also has type-checked forms with the help of typescript 
to help and guide the developer to build a robust form solution.

Let's look at a bit of code first and then start breaking it down alongside the 
usage of the different utilities the library provides:

include::partial$forms/code/rhf-step-one.adoc[]

When it comes to validations its API is quite simple and extendable nevertheless:

include::partial$forms/code/rhf-step-two.adoc[]

And, we can rest assured that the way the form re-renders is optimal, it doesn't render 
the whole thing, it follows React principles in order to render itself correctly.

== Validation

React Hook Form makes form validation easy by aligning with the existing 
https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Form_validation[HTML standard 
for form validation]

The list of supported validation rules are:

- required
- min
- max
- minLength
- maxLength
- pattern
- validate

`validate` is pretty interesting since you can feed your custom validation logic to it:

include::partial$forms/code/rhf-validations-one.adoc[]

Besides feeding custom validations, if we need to account for more complex cases such 
as two fields being validated between one and other, we can make use of the `submit` 
function we ourselves feed into `handleSubmit`:

include::partial$forms/code/rhf-validations-complex.adoc[]

However, using **schema validations** with stuff like `Yup` or `Zod` is a much cleaner 
and scalable approach:

First, you have to install the resolver for the respective schema validator (in our case 
we will leverage yup): `pnpm i @hookform/resolvers yup`.

include::partial$forms/code/rhf-validations-schema.adoc[]

== Integrating with custom and library components

=== Existing Custom Form

If you have an existing form we can integrate seamlessly with the correct functions 
and signatures:

include::partial$forms/code/rhf-integrating-custom.adoc[]

=== Third-party Forms

You should be able to integrate with UI component libraries just fine, if by any 
chance the component does not expose the `ref` you can leverage the `Controller` 
input, he will take care of the registration process.

include::partial$forms/code/rhf-integrating-ui-libraries.adoc[]