== Module Architecture

All modules should follow a specific structure, by adhering to this structure we 
are making sure that we keep our code organized, predictable and more maintainable in 
the long run. Whilst our approach might delve a bit into _too much abstraction_. 
We have to emphasize the idea that the initial setup (and learning curve) might be 
the biggest hurdle, but once you are comfortable with the project, then things should 
fall into place without much issue.

Just know that everything starts from the Web API's `Program.cs` side. We make two 
important calls there:

[source, csharp]
----
builder.Services.InstallModulesFromAssemblies( <1>
    builder.Configuration,
    Modules.Authentication.AssemblyReference.Assembly);

app.InstallEndpointsFromAssemblies( <2>
    app.Configuration,
    Modules.Authentication.AssemblyReference.Assembly);
----
<1> We have different services, and things specific to a module that we have to 
_"install"_ on our app. And it's through this extension method that we can feed all 
the configurations to be loaded into the app, plus sending assembly references that will 
help us scan the whole project to then start registering the different components.
<2> And just like the `services` use case, we also have to scan for different endpoints 
(since we will be using Minimal APIs), and this takes place after the app container has 
been built and we now deal with the HTTP pipeline.

With that in mind, each module should always have its own `IModuleInstaller`. If we 
don't have this, then none of the methods we laid out before will pick up on the respective 
interface to then kickstart further registrations.

[source, csharp]
----
using Common.Library;
using Common.Library.Interfaces;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Modules.Authentication;

public class AuthenticationModuleInstaller : IModuleInstaller
{
    public void InstallModule(IServiceCollection serviceCollection, IConfiguration configuration) <1>
    {
        serviceCollection.InstallServicesFromAssemblies(configuration, AssemblyReference.Assembly); <2>
    }
}

----
<1> The interface will have an `InstallModule` method to which we feed both the `IServiceCollection` 
and the `IConfiguration` objects coming straight from the app. And this method 
ideally should be used to make different additions of different types of services and 
extras to the application.
<2> It's from this specific place that we can then call another extension method called 
`InstallServicesFromAssemblies`. This method follows the same idea as the module approach, 
we can feed an (n) number of assembly targets to it so that it scans them and then runs 
the respective method specific to a `IServiceInstaller`.

One such `IServiceInstaller` would look like this:

[source, csharp]
----
using Common.Library.Interfaces;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Modules.Authentication.GoogleOAuth;

namespace Modules.Authentication.ServiceInstallers;

public class RepositoryServicesInstaller : IServiceInstaller
{
    public void Install(IServiceCollection app, IConfiguration configuration) <1>
    {
        app.AddScoped<IGoogleOAuthRepository, GoogleOAuthRepository>(); <2>
    }
}

----
<1> Under an `Install` method we should have all the specific code that will start saving 
into the DI container of the app all the services that we want to register from the 
module (and that are specific to our sub-domain).
<2> For example, we could have a `RepositoryServicesInstaller` in charge of only registering 
all the repositories that live in the module. And it will only take care of registering that.

In theory we could be creating tons of `IServiceInstaller` implementations each 
specialized on an specific type of service/logging/DI registration onto the app's 
DI container.

And so the way the flow of module installation should follow:

[listing]
----
app => IModuleInstaller => IServiceInstaller

app => IEndpointDefinition
----

**_Assembly Scanning_** is what we are leveraging a ton to make code more concise, 
and less boilerplaity. The key lies at _registering the classes under the right interface_. 
Once you do that, then everything should fall into place, since all the abstracted 
general purpose code is already there. And now integrating and extending should be 
a really mechanical process.