[source, yml]
----
name: CRON Job to Housekeep Google Artifact Registry

on:
  workflow_dispatch: <1>
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC <2>

jobs:
  connect-setup-and-run-script:
    name: Connect and Setup Google Cloud
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Google Cloud authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # JSON key for GCP service account

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Run the script from the .github/scripts folder
      - name: Run custom script
        env: <3>
          SERVICE_NAME: 'kakeibro-api' # Cloud Run service name
          REGION: 'us-central1' # Cloud Run region (e.g., us-central1)
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

        run: |
          chmod +x .github/scripts/image-cleanup.sh <4>
          .github/scripts/image-cleanup.sh <5>

----
<1> If `workflow_dispatch` is stated under the trigger conditions of the action, it will 
allow for us to head to the _Actios_ tab at the repo level and click a button to trigger 
it manually.
<2> GitHub Actions can be configured to run on a CRON manner, great for periodic jobs 
that should run even when we are not there. In our case we will always clean up the 
gcloud artifact registry at midnight, and we will only keep the last 3 tags alive. 
Remember that xref:ci-cd-pipelines.adoc#push-two-tags[we have 2 tags that are the same image], 
meaning that `latest` will take one space, and the following two will be the latest image's 
commit tag and the previous commit's tag. So we are keeping in essence a latest and 
one previous version backup.
<3> Just we keep security in mind and good practices in here as well, we can declare 
env variables at a specific step of a job, and so that Github obfuscates values that 
might come from the _secrets_ vault, we have to assign them like this.