The tutorials that were used in order to find out how to integrate with Google's OAuth 
were:

- https://developers.google.com/api-client-library/dotnet/get_started[Dotnet Library]
- https://developers.google.com/identity/protocols/oauth2/web-server#httprest_1[OAuth for Web Server Applications]
- https://cloud.google.com/resource-manager/docs/creating-managing-projects?visit_id=638731573502905114-2035959981&rd=1[A good way to setup a Google Console App]

First of all, a Google Cloud Project should be created in order to tie it to applications, 
and other integrations with all the services that Google Cloud offers. A **KakeiBro** 
project has been created and that will be the nexus into Google OAuth.

Due to us having to integrate with Google Cloud, we have to keep some sort of data 
that can help us keep track of the user that's on Google Cloud, and that be tied into our 
own data. Hence, we will just make requests to Google, the user will authorize the usage 
of his account and on his behalf we will be then get some metadata from Google and 
use that to then concretize the user registration.

_Meaning we will have to make do with what Google has and we create on the background 
all the data from the user_. It's basically a facade in which we make use of Google 
for the Auth, if everything is okay from their side, we simply get back tokens, enable 
a bit of logic to then use tokens and refresh tokens accordingly.

[NOTE]
====
It would probably be a good idea to leverage Redis and its TTL setting on a record to 
invalidate the token once everything expires. Also, we can leverage Redis and some key 
in there to retrieve the token if it is still valid (send it to the client and then 
have the client not cache it in local storage, but the database always returning that 
and then the client saving it into memory if it doesn't find it).
====

Once the project is created, you have to configure the `Google Auth Platform`. Which is 
one of the services at the _Google Cloud Console_. It's here that you will have to setup 
the service so that we can get a client secret, and a client ID in order to start consuming 
the application. Luckily the setup process is pretty self-explanatory so just follow the steps.

Once that's done, you need to get a Client that will be under the project. However for this 
you have to configure the `Consent Screen`. This requires a logo, alongside links 
for an Application home page, a privacy policy link, and a ToS link. Make sure to 
add all the domains that are used for these links to be also added as part of the 
`Authorized Domains` section.

After this is done, you might have to wait a bit until the consent page state is updated, 
but once it is you can go into the `Clients` tab and then create a client that should be 
for **web**, and it will ask for information in regards to the app, alongside the callback 
URI and the javascript sources that will be authorized. Once the client is created, 
you can go and download all the secrets in a `.json` format. This is extremely sensitive 
information, so add that to a `.gitignore` and never commit them, there's a secret, 
and other information specifically catered to authenticate the client when trying to 
access the Google Auth API.